name: balam_app
description: Marketplace de agrupaciones musicales y clientes.
publish_to: none
version: 1.1.10+10

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.8.1
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  http_parser: ^4.1.2
  flutter_secure_storage: ^9.2.2
  image_picker: ^1.1.2
  google_sign_in: ^6.2.1
  mobile_scanner: ^7.0.1
  qr_flutter: ^4.1.0
  url_launcher: ^6.3.1
  video_player: ^2.11.1
  firebase_core: ^4.15.0
  firebase_messaging: ^16.7.0
  flutter_local_notifications: ^22.3.1
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/avatars/
    - assets/branding/
    - assets/themes/
