"""initial Balam schema

Revision ID: 20260909_0001
Revises: 
Create Date: 2026-09-09 10:37:22.628927
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '20260909_0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('musician', 'client', 'admin', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('avatar_choices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('preset', sa.String(length=40), nullable=False),
    sa.Column('color', sa.String(length=9), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_avatar_choices_user_id'), 'avatar_choices', ['user_id'], unique=True)
    op.create_table('client_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('admin_phone', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('municipality', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('musical_tastes', sa.Text(), nullable=False),
    sa.Column('favorite_groups', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_profiles_city'), 'client_profiles', ['city'], unique=False)
    op.create_index(op.f('ix_client_profiles_municipality'), 'client_profiles', ['municipality'], unique=False)
    op.create_index(op.f('ix_client_profiles_state'), 'client_profiles', ['state'], unique=False)
    op.create_index(op.f('ix_client_profiles_user_id'), 'client_profiles', ['user_id'], unique=True)
    op.create_table('musician_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('contact_name', sa.String(length=120), nullable=False),
    sa.Column('admin_phone', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('municipality', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('group_name', sa.String(length=180), nullable=False),
    sa.Column('group_type', sa.String(length=100), nullable=False),
    sa.Column('musical_style', sa.String(length=180), nullable=False),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('hourly_rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('includes_sound', sa.Boolean(), nullable=False),
    sa.Column('subwoofer_count', sa.Integer(), nullable=False),
    sa.Column('mid_speaker_count', sa.Integer(), nullable=False),
    sa.Column('equipment_brands', sa.Text(), nullable=False),
    sa.Column('audience_capacity', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_musician_profiles_city'), 'musician_profiles', ['city'], unique=False)
    op.create_index(op.f('ix_musician_profiles_group_name'), 'musician_profiles', ['group_name'], unique=False)
    op.create_index(op.f('ix_musician_profiles_group_type'), 'musician_profiles', ['group_type'], unique=False)
    op.create_index(op.f('ix_musician_profiles_municipality'), 'musician_profiles', ['municipality'], unique=False)
    op.create_index(op.f('ix_musician_profiles_musical_style'), 'musician_profiles', ['musical_style'], unique=False)
    op.create_index(op.f('ix_musician_profiles_state'), 'musician_profiles', ['state'], unique=False)
    op.create_index(op.f('ix_musician_profiles_user_id'), 'musician_profiles', ['user_id'], unique=True)
    op.create_table('password_reset_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_codes_expires_at'), 'password_reset_codes', ['expires_at'], unique=False)
    op.create_index(op.f('ix_password_reset_codes_user_id'), 'password_reset_codes', ['user_id'], unique=False)
    op.create_table('rules_acceptances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rules_type', sa.String(length=80), nullable=False),
    sa.Column('rules_version', sa.String(length=80), nullable=False),
    sa.Column('group_name_snapshot', sa.String(length=180), nullable=True),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'rules_type', 'rules_version')
    )
    op.create_index(op.f('ix_rules_acceptances_rules_type'), 'rules_acceptances', ['rules_type'], unique=False)
    op.create_index(op.f('ix_rules_acceptances_rules_version'), 'rules_acceptances', ['rules_version'], unique=False)
    op.create_index(op.f('ix_rules_acceptances_user_id'), 'rules_acceptances', ['user_id'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('musician_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('venue', sa.String(length=300), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client_profiles.id'], ),
    sa.ForeignKeyConstraint(['musician_id'], ['musician_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('musician_id', 'event_date')
    )
    op.create_index(op.f('ix_bookings_client_id'), 'bookings', ['client_id'], unique=False)
    op.create_index(op.f('ix_bookings_event_date'), 'bookings', ['event_date'], unique=False)
    op.create_index(op.f('ix_bookings_musician_id'), 'bookings', ['musician_id'], unique=False)
    op.create_table('client_avatars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_avatars_client_id'), 'client_avatars', ['client_id'], unique=True)
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('musician_id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.Enum('profile_photo', 'photo', 'video', name='mediatype'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['musician_id'], ['musician_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('musician_id', 'media_type', 'position')
    )
    op.create_index(op.f('ix_media_musician_id'), 'media', ['musician_id'], unique=False)
    op.create_table('musician_busy_dates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('musician_id', sa.Integer(), nullable=False),
    sa.Column('busy_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['musician_id'], ['musician_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('musician_id', 'busy_date')
    )
    op.create_index(op.f('ix_musician_busy_dates_busy_date'), 'musician_busy_dates', ['busy_date'], unique=False)
    op.create_index(op.f('ix_musician_busy_dates_musician_id'), 'musician_busy_dates', ['musician_id'], unique=False)
    op.create_table('booking_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('musician_id', sa.Integer(), nullable=False),
    sa.Column('agreed_duration', sa.Float(), nullable=False),
    sa.Column('punctuality', sa.Float(), nullable=False),
    sa.Column('uniform', sa.Float(), nullable=False),
    sa.Column('atmosphere', sa.Float(), nullable=False),
    sa.Column('kindness', sa.Float(), nullable=False),
    sa.Column('song_requests', sa.Float(), nullable=False),
    sa.Column('would_hire_again', sa.Float(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['musician_id'], ['musician_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_reviews_booking_id'), 'booking_reviews', ['booking_id'], unique=True)
    op.create_index(op.f('ix_booking_reviews_musician_id'), 'booking_reviews', ['musician_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('sender_user_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_booking_id'), 'chat_messages', ['booking_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_sender_user_id'), 'chat_messages', ['sender_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_messages_sender_user_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_booking_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_booking_reviews_musician_id'), table_name='booking_reviews')
    op.drop_index(op.f('ix_booking_reviews_booking_id'), table_name='booking_reviews')
    op.drop_table('booking_reviews')
    op.drop_index(op.f('ix_musician_busy_dates_musician_id'), table_name='musician_busy_dates')
    op.drop_index(op.f('ix_musician_busy_dates_busy_date'), table_name='musician_busy_dates')
    op.drop_table('musician_busy_dates')
    op.drop_index(op.f('ix_media_musician_id'), table_name='media')
    op.drop_table('media')
    op.drop_index(op.f('ix_client_avatars_client_id'), table_name='client_avatars')
    op.drop_table('client_avatars')
    op.drop_index(op.f('ix_bookings_musician_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_event_date'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_client_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_rules_acceptances_user_id'), table_name='rules_acceptances')
    op.drop_index(op.f('ix_rules_acceptances_rules_version'), table_name='rules_acceptances')
    op.drop_index(op.f('ix_rules_acceptances_rules_type'), table_name='rules_acceptances')
    op.drop_table('rules_acceptances')
    op.drop_index(op.f('ix_password_reset_codes_user_id'), table_name='password_reset_codes')
    op.drop_index(op.f('ix_password_reset_codes_expires_at'), table_name='password_reset_codes')
    op.drop_table('password_reset_codes')
    op.drop_index(op.f('ix_musician_profiles_user_id'), table_name='musician_profiles')
    op.drop_index(op.f('ix_musician_profiles_state'), table_name='musician_profiles')
    op.drop_index(op.f('ix_musician_profiles_musical_style'), table_name='musician_profiles')
    op.drop_index(op.f('ix_musician_profiles_municipality'), table_name='musician_profiles')
    op.drop_index(op.f('ix_musician_profiles_group_type'), table_name='musician_profiles')
    op.drop_index(op.f('ix_musician_profiles_group_name'), table_name='musician_profiles')
    op.drop_index(op.f('ix_musician_profiles_city'), table_name='musician_profiles')
    op.drop_table('musician_profiles')
    op.drop_index(op.f('ix_client_profiles_user_id'), table_name='client_profiles')
    op.drop_index(op.f('ix_client_profiles_state'), table_name='client_profiles')
    op.drop_index(op.f('ix_client_profiles_municipality'), table_name='client_profiles')
    op.drop_index(op.f('ix_client_profiles_city'), table_name='client_profiles')
    op.drop_table('client_profiles')
    op.drop_index(op.f('ix_avatar_choices_user_id'), table_name='avatar_choices')
    op.drop_table('avatar_choices')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
